### ISSUE TITLE
Add a link to a survey at the end of each tutorial.

### ISSUE THREAD

**Issue by daverick** [loriking/tutorials#2]
To be able to make the tutorials better and start a good feedback loop, a link to a survey about this particular tutorial at the end would be useful.

Get some feedback on the tutorial
* completion
* time to completion
* did you learn something?
* was it too hard?
* ...) 

and some information about the user
* general programming level 
* python programming level

**Comment by loriking** [comment]
This is a great idea.  Question 11 is ambiguous. Are we asking them how do they perceive their level after the tutorial?  Another way to ask this question is "How comfortable are you that you can do X?" (With X being something they learned in the tutorial.)

**Comment by daverick** [comment]
- Looks like the question 11 has been cut. It was a question about the level of 🦄 and 🌈. 
- Regarding "How comfortable are you that you can do X?" , the questionnaire is generic for all the tutorials, so unless having a pro account on typeform it is not possible to do a different question depending on the answer to another question.
- if you commit your fixes for #3 I can add the link to the form at the end of the tutorial.
